version: "3"

services:
  postgresql10:
    container_name: postgresql10
    image: postgres:11.9
    command: postgres -c 'max_connections=500'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: always
    shm_size: "256mb"
    ports:
      - 5432:5432
